### ISSUE TITLE
Cannot install requirements

### ISSUE THREAD

**Issue by DSimonne** [jackey-qiu/DaFy#2]
Hi,

I cannot install the pycifrw package to use your code.
I tried with `pip install pycifrw` but it raises the following error:

```
Collecting pycifrw
  Using cached PyCifRW-4.4.3.tar.gz (1.1 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycifrw
  Building wheel for pycifrw (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/CifFile
      copying src/__init__.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/CifFile_module.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/yapps3_compiled_rt.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_1_1.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_1_0.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_STAR2.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_2_0.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/StarFile.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/TypeContentsParser.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/parsetab.py -> build/lib.linux-x86_64-3.9/CifFile
      creating build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/drel_ast_yacc.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/drel_runtime.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/drel_lex.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/py_from_ast.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/parsetab.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/__init__.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      running build_ext
      building 'CifFile.StarScan' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/src
      creating build/temp.linux-x86_64-3.9/src/lib
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c src/lib/lex.yy.c -o build/temp.linux-x86_64-3.9/src/lib/lex.yy.o
      star.l: In function ‘star_scanner’:
      star.l:111:26: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
      lex.yy.c:195:36: warning: comparison of integer expressions of different signedness: ‘int’ and ‘yy_size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
      lex.yy.c:213:9: note: in expansion of macro ‘YY_LESS_LINENO’
      star.l:117:24: note: in expansion of macro ‘yyless’
      star.l:136:26: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
      lex.yy.c:195:36: warning: comparison of integer expressions of different signedness: ‘int’ and ‘yy_size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
      lex.yy.c:213:9: note: in expansion of macro ‘YY_LESS_LINENO’
      star.l:142:24: note: in expansion of macro ‘yyless’
      At top level:
      lex.yy.c:1394:16: warning: ‘input’ defined but not used [-Wunused-function]
      lex.yy.c:1349:17: warning: ‘yyunput’ defined but not used [-Wunused-function]
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c src/lib/py_star_scan.c -o build/temp.linux-x86_64-3.9/src/lib/py_star_scan.o
      src/lib/py_star_scan.c:2:10: fatal error: Python.h: No such file or directory
          2 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycifrw
  Running setup.py clean for pycifrw
Failed to build pycifrw
Installing collected packages: pycifrw
  Running setup.py install for pycifrw ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pycifrw did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/CifFile
      copying src/__init__.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/CifFile_module.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/yapps3_compiled_rt.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_1_1.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_1_0.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_STAR2.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/YappsStarParser_2_0.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/StarFile.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/TypeContentsParser.py -> build/lib.linux-x86_64-3.9/CifFile
      copying src/parsetab.py -> build/lib.linux-x86_64-3.9/CifFile
      creating build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/drel_ast_yacc.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/drel_runtime.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/drel_lex.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/py_from_ast.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/parsetab.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      copying src/drel/__init__.py -> build/lib.linux-x86_64-3.9/CifFile/drel
      running build_ext
      building 'CifFile.StarScan' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/src
      creating build/temp.linux-x86_64-3.9/src/lib
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c src/lib/lex.yy.c -o build/temp.linux-x86_64-3.9/src/lib/lex.yy.o
      star.l: In function ‘star_scanner’:
      star.l:111:26: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
      lex.yy.c:195:36: warning: comparison of integer expressions of different signedness: ‘int’ and ‘yy_size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
      lex.yy.c:213:9: note: in expansion of macro ‘YY_LESS_LINENO’
      star.l:117:24: note: in expansion of macro ‘yyless’
      star.l:136:26: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
      lex.yy.c:195:36: warning: comparison of integer expressions of different signedness: ‘int’ and ‘yy_size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
      lex.yy.c:213:9: note: in expansion of macro ‘YY_LESS_LINENO’
      star.l:142:24: note: in expansion of macro ‘yyless’
      At top level:
      lex.yy.c:1394:16: warning: ‘input’ defined but not used [-Wunused-function]
      lex.yy.c:1349:17: warning: ‘yyunput’ defined but not used [-Wunused-function]
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c src/lib/py_star_scan.c -o build/temp.linux-x86_64-3.9/src/lib/py_star_scan.o
      src/lib/py_star_scan.c:2:10: fatal error: Python.h: No such file or directory
          2 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycifrw

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Do you have any idea on to how to fix this error ?
I am running on Debian 11, all the other requirements are OK.

**Comment by DSimonne** [comment]
I had the same kind of error with `wxPython`

**Comment by jackey-qiu** [comment]
@DSimonne 
Hi David,
I already removed the dependency of wxpython. So you don't need this anymore. As for the pycifrw issue, I don't know how to solve it. I was able to install it on both Mac and Win32, but never tried to install it on a linux machine. Could you try to install it with anaconda. See more from this link: https://anaconda.org/conda-forge/pycifrw
Please let me know if you make it with conda install.
Jackey

**Comment by DSimonne** [comment]
Hi, I will try with anaconda and hope it won't destroy my environment ^^

I also add a problem with qt plugins 

Info: Could not import weave, turbo off
Cannot initialize filter fcidecomp: File not found
Info: Could not import weave, turbo off
QObject::moveToThread: Current thread (0x27afcd0) is not the object's thread (0x5ce98a0).
Cannot move to target thread (0x27afcd0)

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/david/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

*** SIGABRT received at time=1643910951 on cpu 1 ***
PC: @     0x7f35567da891  (unknown)  raise
    @     0x7f355697b200  (unknown)  (unknown)
    @       0x3000000018  (unknown)  (unknown)
    @ ... and at least 1 more frames
[2022-02-03 18:55:51,750 E 208387 208387] logging.cc:317: *** SIGABRT received at time=1643910951 on cpu 1 ***
[2022-02-03 18:55:51,750 E 208387 208387] logging.cc:317: PC: @     0x7f35567da891  (unknown)  raise
[2022-02-03 18:55:51,751 E 208387 208387] logging.cc:317:     @     0x7f355697b200  (unknown)  (unknown)
[2022-02-03 18:55:51,753 E 208387 208387] logging.cc:317:     @       0x3000000018  (unknown)  (unknown)
[2022-02-03 18:55:51,753 E 208387 208387] logging.cc:317:     @ ... and at least 1 more frames
Fatal Python error: Aborted

Stack (most recent call first):
  File "/home/david/Packages/DaFy/projects/superrod/SuPerRod_GUI.py", line 3238 in <module>
Aborted
```

**Comment by jackey-qiu** [comment]
@DSimonne 
uninstall opencv-python, then install opencv-python-headless instead. It should work then.

**Comment by DSimonne** [comment]
Hi,

Just to say that I managed to install your package, just tried again today with latest GitHub version and it worked.
Not sure what happened.

I had this error though:

```python
david@pc-momonne:~/Packages/DaFy/projects/superrod$ python3 SuPerRod_GUI.py 
Info: Could not import weave, turbo off
Info: Could not import weave, turbo off
Traceback (most recent call last):
  File "/home/david/Packages/DaFy/projects/superrod/SuPerRod_GUI.py", line 3242, in <module>
    myWin = MyMainWindow()
  File "/home/david/Packages/DaFy/projects/superrod/SuPerRod_GUI.py", line 700, in __init__
    uic.loadUi(os.path.join(DaFy_path,'projects','SuperRod','superrod_gui.ui'),self)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/Loader/loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt5/uic/uiparser.py", line 1020, in parse
    document = parse(filename)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/Packages/DaFy/projects/SuperRod/superrod_gui.ui'
```

So I copied the folder `/home/david/Packages/DaFy/projects/superrod` to `/home/david/Packages/DaFy/projects/SuperRod`
and it works !

**Comment by jackey-qiu** [comment]
It is related to miscapitalized issue for the path of superrod. I fixed it now. Strange, I don't have this issue before.
